import type { User, Post, PostComment, Connection, Cluster, ChatMessage, CallState } from '@/context/PostContext';
import type { Track, Album, Playlist } from '@/context/MusicContext';
import type { NotificationNode } from '@/context/NotificationContext';

export const MOCK_CURRENT_USER: User = {
  $id: 'user_001',
  name: 'Alex Rivers',
  username: 'alex_rivers',
  email: 'alex@vimore.app',
  avatar: 'https://picsum.photos/seed/alex_rivers/200/200',
  cover: 'https://picsum.photos/seed/alex_cover/800/300',
  isVerified: true,
  followers: 12400,
  following: 380,
  friendsCount: 210,
  posts: 94,
  bio: 'Creator. Dreamer. Building the future one post at a time.',
  category: 'Lifestyle',
  gender: 'Male',
  nationality: 'US',
  goldBalance: 1200,
  diamondBalance: 85,
  starBalance: 320,
  referralCount: 14,
  role: 'SUPER',
  joinDate: '2024-01-15',
  isEmailVerified: true,
  hasEverBeenVerified: true,
  language: 'en',
};

export const MOCK_USERS: User[] = [
  {
    $id: 'user_002',
    name: 'Maya Chen',
    username: 'maya_chen',
    avatar: 'https://picsum.photos/seed/maya_chen/200/200',
    isVerified: true,
    followers: 89200,
    following: 412,
    bio: 'Digital artist & content creator 🎨',
    category: 'Art',
    goldBalance: 4500,
    diamondBalance: 210,
    starBalance: 800,
    role: 'USER',
  },
  {
    $id: 'user_003',
    name: 'Jordan Blake',
    username: 'jordan_blake',
    avatar: 'https://picsum.photos/seed/jordan_blake/200/200',
    isVerified: false,
    followers: 3200,
    following: 290,
    bio: 'Music producer & beatmaker 🎵',
    category: 'Music',
    goldBalance: 800,
    diamondBalance: 30,
    starBalance: 90,
    role: 'USER',
  },
  {
    $id: 'user_004',
    name: 'Priya Sharma',
    username: 'priya_sharma',
    avatar: 'https://picsum.photos/seed/priya_sharma/200/200',
    isVerified: true,
    followers: 54000,
    following: 170,
    bio: 'Wellness coach & yoga instructor 🧘',
    category: 'Wellness',
    goldBalance: 2200,
    diamondBalance: 120,
    starBalance: 450,
    role: 'USER',
  },
  {
    $id: 'user_005',
    name: 'Leo Martinez',
    username: 'leo_martinez',
    avatar: 'https://picsum.photos/seed/leo_martinez/200/200',
    isVerified: false,
    followers: 7800,
    following: 530,
    bio: 'Travel vlogger 🌍 | 40 countries & counting',
    category: 'Travel',
    goldBalance: 600,
    diamondBalance: 20,
    starBalance: 70,
    role: 'USER',
  },
  {
    $id: 'user_006',
    name: 'Sofia Andersen',
    username: 'sofia_andersen',
    avatar: 'https://picsum.photos/seed/sofia_andersen/200/200',
    isVerified: true,
    followers: 31000,
    following: 220,
    bio: 'Fashion forward. Always. 👗',
    category: 'Fashion',
    goldBalance: 1800,
    diamondBalance: 95,
    starBalance: 300,
    role: 'USER',
  },
];

const MOCK_COMMENTS: PostComment[] = [
  {
    $id: 'comment_001',
    userId: 'user_002',
    userName: 'Maya Chen',
    userAvatar: 'https://picsum.photos/seed/maya_chen/200/200',
    text: 'This is absolutely stunning! 🔥',
    time: '2h ago',
    timestamp: Date.now() - 7200000,
  },
  {
    $id: 'comment_002',
    userId: 'user_003',
    userName: 'Jordan Blake',
    userAvatar: 'https://picsum.photos/seed/jordan_blake/200/200',
    text: 'Love the vibe here, keep it going!',
    time: '1h ago',
    timestamp: Date.now() - 3600000,
  },
  {
    $id: 'comment_003',
    userId: 'user_004',
    userName: 'Priya Sharma',
    userAvatar: 'https://picsum.photos/seed/priya_sharma/200/200',
    text: 'So inspiring 💫',
    time: '30m ago',
    timestamp: Date.now() - 1800000,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    $id: 'post_001',
    user: MOCK_USERS[0],
    content: 'Just finished a 12-hour session and this piece is finally done. Art is never really finished, just abandoned at the right moment. ✨ What do you think?',
    time: '2h ago',
    likes: 1842,
    unlikes: 12,
    comments: 3,
    shares: 234,
    views: 14200,
    image: 'https://picsum.photos/seed/post001/800/600',
    commentNodes: MOCK_COMMENTS,
  },
  {
    $id: 'post_002',
    user: MOCK_USERS[1],
    content: 'New beat dropping tonight 🎵 Been working on this one for weeks. The sample is from a vinyl I found at a flea market in Tokyo. Pure gold.',
    time: '4h ago',
    likes: 3210,
    unlikes: 8,
    comments: 87,
    shares: 412,
    views: 28900,
    image: 'https://picsum.photos/seed/post002/800/600',
  },
  {
    $id: 'post_003',
    user: MOCK_USERS[2],
    content: 'Morning flow at sunrise. There is something magical about starting the day in complete stillness before the world wakes up. 5am club, who else? 🧘‍♀️',
    time: '6h ago',
    likes: 5670,
    unlikes: 3,
    comments: 142,
    shares: 889,
    views: 41000,
    image: 'https://picsum.photos/seed/post003/800/600',
  },
  {
    $id: 'post_004',
    user: MOCK_USERS[3],
    content: 'Santorini at golden hour hits different 🌅 This was day 3 of the trip — still cannot believe how blue that water is. Full travel guide dropping this week.',
    time: '1d ago',
    likes: 9120,
    unlikes: 21,
    comments: 310,
    shares: 1450,
    views: 88000,
    image: 'https://picsum.photos/seed/post004/800/600',
  },
  {
    $id: 'post_005',
    user: MOCK_USERS[4],
    content: 'Spring collection preview 🌸 Which look is your favourite? Drop a number below! The whole line is sustainable this season — felt like the right move.',
    time: '1d ago',
    likes: 4380,
    unlikes: 5,
    comments: 218,
    shares: 670,
    views: 32000,
    image: 'https://picsum.photos/seed/post005/800/600',
  },
  {
    $id: 'post_006',
    user: MOCK_CURRENT_USER,
    content: 'Every great creator started with zero followers. The gap between where you are and where you want to be is just time and consistency. Keep going. 💪',
    time: '2d ago',
    likes: 2100,
    unlikes: 4,
    comments: 95,
    shares: 380,
    views: 19500,
  },
  {
    $id: 'post_007',
    user: MOCK_USERS[0],
    content: 'New series starting tomorrow — "Digital Dreams" — 30 pieces in 30 days exploring the intersection of AI and human creativity. Follow along 🎨',
    time: '3d ago',
    likes: 7800,
    unlikes: 15,
    comments: 420,
    shares: 1200,
    views: 62000,
    image: 'https://picsum.photos/seed/post007/800/600',
    isBoosted: true,
    boostTargetViews: 100000,
    boostCurrentViews: 62000,
  },
  {
    $id: 'post_008',
    user: MOCK_USERS[1],
    content: 'Locked content available for subscribers 🔒 My private production masterclass — 4 hours of raw session footage.',
    time: '4d ago',
    likes: 1900,
    unlikes: 7,
    comments: 64,
    shares: 150,
    views: 11000,
    isLocked: true,
    unlockPrice: 50,
  },
];

export const MOCK_CONNECTIONS: Connection[] = [
  {
    ...MOCK_USERS[0],
    isGroup: false,
    followsYou: true,
    isOnline: true,
    lastMessage: 'Love your latest work!',
    lastTime: '2m ago',
  },
  {
    ...MOCK_USERS[1],
    isGroup: false,
    followsYou: true,
    isOnline: false,
    lastMessage: 'Are you coming to the show?',
    lastTime: '1h ago',
  },
  {
    ...MOCK_USERS[2],
    isGroup: false,
    followsYou: false,
    isOnline: true,
    lastMessage: 'Great session today!',
    lastTime: '3h ago',
  },
  {
    ...MOCK_USERS[3],
    isGroup: false,
    followsYou: true,
    isOnline: false,
    lastMessage: 'Check out this place I found',
    lastTime: 'Yesterday',
  },
  {
    ...MOCK_USERS[4],
    isGroup: false,
    followsYou: false,
    isOnline: true,
    lastMessage: 'The new drop is 🔥',
    lastTime: 'Yesterday',
  },
];

export const MOCK_CLUSTERS: Cluster[] = [
  {
    $id: 'cluster_001',
    name: 'Creator Collective',
    adminUsername: 'alex_rivers',
    avatar: 'https://picsum.photos/seed/cluster_001/200/200',
    members: [MOCK_CURRENT_USER, ...MOCK_USERS.slice(0, 3)],
    isGroup: true,
  },
  {
    $id: 'cluster_002',
    name: 'Music Producers Hub',
    adminUsername: 'jordan_blake',
    avatar: 'https://picsum.photos/seed/cluster_002/200/200',
    members: [MOCK_CURRENT_USER, MOCK_USERS[1], MOCK_USERS[4]],
    isGroup: true,
  },
];

export const MOCK_CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  maya_chen: [
    { $id: 'msg_001', sender: 'them', senderId: 'user_002', senderName: 'Maya Chen', senderAvatar: 'https://picsum.photos/seed/maya_chen/200/200', text: 'Hey! Love your latest post 🔥', time: '10:24 AM', status: 'read', type: 'text' },
    { $id: 'msg_002', sender: 'me', senderId: 'user_001', text: 'Thank you so much! Working on something even bigger', time: '10:26 AM', status: 'read', type: 'text' },
    { $id: 'msg_003', sender: 'them', senderId: 'user_002', senderName: 'Maya Chen', senderAvatar: 'https://picsum.photos/seed/maya_chen/200/200', text: 'Can not wait to see it! Collab soon?', time: '10:27 AM', status: 'read', type: 'text' },
    { $id: 'msg_004', sender: 'me', senderId: 'user_001', text: 'Absolutely! Let me DM you the concept 🎨', time: '10:30 AM', status: 'delivered', type: 'text' },
  ],
  jordan_blake: [
    { $id: 'msg_010', sender: 'them', senderId: 'user_003', senderName: 'Jordan Blake', senderAvatar: 'https://picsum.photos/seed/jordan_blake/200/200', text: 'Are you coming to the show on Friday?', time: 'Yesterday', status: 'read', type: 'text' },
    { $id: 'msg_011', sender: 'me', senderId: 'user_001', text: 'Would not miss it!', time: 'Yesterday', status: 'read', type: 'text' },
  ],
  cluster_001: [
    { $id: 'msg_020', sender: 'them', senderId: 'user_002', senderName: 'Maya Chen', senderAvatar: 'https://picsum.photos/seed/maya_chen/200/200', text: 'When is the next meetup? 🙌', time: '2h ago', status: 'read', type: 'text' },
    { $id: 'msg_021', sender: 'them', senderId: 'user_003', senderName: 'Jordan Blake', senderAvatar: 'https://picsum.photos/seed/jordan_blake/200/200', text: 'I am free all next week', time: '1h ago', status: 'read', type: 'text' },
    { $id: 'msg_022', sender: 'me', senderId: 'user_001', text: 'Let us do Saturday afternoon!', time: '45m ago', status: 'delivered', type: 'text' },
  ],
};

export const MOCK_STORIES = [
  {
    $id: 'story_001',
    user: MOCK_USERS[0],
    segments: [
      { id: 'seg_001', type: 'image', url: 'https://picsum.photos/seed/story001/400/700', caption: 'Studio vibes ✨', duration: 5 },
    ],
    expiry: new Date(Date.now() + 72000000).toISOString(),
    viewCount: 1240,
  },
  {
    $id: 'story_002',
    user: MOCK_USERS[1],
    segments: [
      { id: 'seg_002', type: 'image', url: 'https://picsum.photos/seed/story002/400/700', caption: 'New beat 🎵', duration: 5 },
    ],
    expiry: new Date(Date.now() + 50000000).toISOString(),
    viewCount: 870,
  },
  {
    $id: 'story_003',
    user: MOCK_USERS[2],
    segments: [
      { id: 'seg_003', type: 'image', url: 'https://picsum.photos/seed/story003/400/700', caption: 'Morning flow 🧘', duration: 5 },
    ],
    expiry: new Date(Date.now() + 40000000).toISOString(),
    viewCount: 3200,
  },
  {
    $id: 'story_004',
    user: MOCK_CURRENT_USER,
    segments: [
      { id: 'seg_004', type: 'image', url: 'https://picsum.photos/seed/myStory/400/700', caption: 'My latest ✌️', duration: 5 },
    ],
    expiry: new Date(Date.now() + 60000000).toISOString(),
    viewCount: 512,
  },
];

export const MOCK_NOTIFICATIONS: NotificationNode[] = [
  {
    id: 'notif_001',
    type: 'SOCIAL',
    title: 'Maya Chen liked your post',
    content: '"Just finished a 12-hour session..."',
    time: '2m ago',
    isRead: false,
    recipientId: 'alex_rivers',
    avatar: 'https://picsum.photos/seed/maya_chen/200/200',
    postId: 'post_001',
  },
  {
    id: 'notif_002',
    type: 'SOCIAL',
    title: 'Jordan Blake started following you',
    content: 'You have a new follower',
    time: '15m ago',
    isRead: false,
    recipientId: 'alex_rivers',
    avatar: 'https://picsum.photos/seed/jordan_blake/200/200',
    targetUsername: 'jordan_blake',
  },
  {
    id: 'notif_003',
    type: 'POST',
    title: 'Priya Sharma commented on your post',
    content: '"So inspiring 💫"',
    time: '1h ago',
    isRead: false,
    recipientId: 'alex_rivers',
    avatar: 'https://picsum.photos/seed/priya_sharma/200/200',
    postId: 'post_006',
  },
  {
    id: 'notif_004',
    type: 'SONIC',
    title: 'Your track is trending',
    content: '"Midnight Session" hit 10K streams 🎵',
    time: '3h ago',
    isRead: true,
    recipientId: 'alex_rivers',
  },
  {
    id: 'notif_005',
    type: 'SYSTEM',
    title: 'Welcome to ViMore',
    content: 'Your profile is all set. Start creating!',
    time: '2d ago',
    isRead: true,
    recipientId: 'alex_rivers',
  },
];

export const MOCK_TRACKS: Track[] = [
  { id: 'track_001', title: 'Midnight Session', artist: 'Jordan Blake', artistUsername: 'jordan_blake', artistFollowers: 3200, cover: 'https://picsum.photos/seed/track001/300/300', duration: 213, streams: '14.2K', likes: 840, isBoosted: true },
  { id: 'track_002', title: 'Golden Hour', artist: 'Maya Chen', artistUsername: 'maya_chen', artistFollowers: 89200, cover: 'https://picsum.photos/seed/track002/300/300', duration: 187, streams: '88K', likes: 4200 },
  { id: 'track_003', title: 'Still Water', artist: 'Priya Sharma', artistUsername: 'priya_sharma', artistFollowers: 54000, cover: 'https://picsum.photos/seed/track003/300/300', duration: 245, streams: '32K', likes: 1900 },
  { id: 'track_004', title: 'Wanderlust', artist: 'Leo Martinez', artistUsername: 'leo_martinez', artistFollowers: 7800, cover: 'https://picsum.photos/seed/track004/300/300', duration: 198, streams: '8.4K', likes: 560 },
  { id: 'track_005', title: 'Neon Dreams', artist: 'Sofia Andersen', artistUsername: 'sofia_andersen', artistFollowers: 31000, cover: 'https://picsum.photos/seed/track005/300/300', duration: 220, streams: '21K', likes: 1100 },
  { id: 'track_006', title: 'Rise Up', artist: 'Alex Rivers', artistUsername: 'alex_rivers', artistFollowers: 12400, cover: 'https://picsum.photos/seed/track006/300/300', duration: 203, streams: '5.1K', likes: 380 },
  { id: 'track_007', title: 'City Lights', artist: 'Jordan Blake', artistUsername: 'jordan_blake', artistFollowers: 3200, cover: 'https://picsum.photos/seed/track007/300/300', duration: 176, streams: '9.8K', likes: 670 },
  { id: 'track_008', title: 'Ocean Drive', artist: 'Maya Chen', artistUsername: 'maya_chen', artistFollowers: 89200, cover: 'https://picsum.photos/seed/track008/300/300', duration: 231, streams: '44K', likes: 2800 },
];

export const MOCK_ALBUMS: Album[] = [
  {
    id: 'album_001',
    title: 'Midnight Sessions Vol. 1',
    artist: 'Jordan Blake',
    artistUsername: 'jordan_blake',
    cover: 'https://picsum.photos/seed/album001/300/300',
    year: '2024',
    tracks: 8,
    totalStreams: '124K',
    songs: MOCK_TRACKS.filter(t => t.artistUsername === 'jordan_blake'),
  },
  {
    id: 'album_002',
    title: 'Golden Light',
    artist: 'Maya Chen',
    artistUsername: 'maya_chen',
    cover: 'https://picsum.photos/seed/album002/300/300',
    year: '2024',
    tracks: 6,
    totalStreams: '890K',
    songs: MOCK_TRACKS.filter(t => t.artistUsername === 'maya_chen'),
  },
  {
    id: 'album_003',
    title: 'Inner Peace',
    artist: 'Priya Sharma',
    artistUsername: 'priya_sharma',
    cover: 'https://picsum.photos/seed/album003/300/300',
    year: '2023',
    tracks: 10,
    totalStreams: '340K',
    songs: MOCK_TRACKS.filter(t => t.artistUsername === 'priya_sharma'),
  },
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: 'playlist_001',
    title: 'Morning Chill',
    creator: 'alex_rivers',
    cover: 'https://picsum.photos/seed/playlist001/300/300',
    totalStreams: '42K',
    songs: [MOCK_TRACKS[2], MOCK_TRACKS[1], MOCK_TRACKS[4]],
    description: 'Perfect for starting your day right',
  },
  {
    id: 'playlist_002',
    title: 'Late Night Beats',
    creator: 'jordan_blake',
    cover: 'https://picsum.photos/seed/playlist002/300/300',
    totalStreams: '78K',
    songs: [MOCK_TRACKS[0], MOCK_TRACKS[6], MOCK_TRACKS[4]],
    description: 'Beats for the night owls',
  },
  {
    id: 'playlist_003',
    title: 'Focus Flow',
    creator: 'priya_sharma',
    cover: 'https://picsum.photos/seed/playlist003/300/300',
    totalStreams: '55K',
    songs: [MOCK_TRACKS[2], MOCK_TRACKS[7], MOCK_TRACKS[5]],
    description: 'Deep focus & productivity',
  },
];

export const MOCK_CAMPAIGNS = [
  {
    $id: 'camp_001',
    title: 'Summer Boost 2024',
    targetUrl: 'https://vimore.app',
    budget: 500,
    isActive: true,
    impressions: 12400,
    clicks: 840,
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    $id: 'camp_002',
    title: 'Creator Fund Promo',
    targetUrl: 'https://vimore.app/join',
    budget: 250,
    isActive: false,
    impressions: 5600,
    clicks: 320,
    timestamp: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
];

export const MOCK_PAYMENT_REQUESTS = [
  {
    $id: 'pay_001',
    userId: 'user_003',
    username: 'jordan_blake',
    packageName: 'Diamond Pack 100',
    amount: '25',
    currency: 'USD',
    code: 'VBC-X92A',
    status: 'PENDING',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    $id: 'pay_002',
    userId: 'user_005',
    username: 'leo_martinez',
    packageName: 'Gold Pack 500',
    amount: '10',
    currency: 'USD',
    code: 'VBC-M44B',
    status: 'APPROVED',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const MOCK_WITHDRAWALS = [
  {
    $id: 'wd_001',
    userId: 'user_002',
    username: 'maya_chen',
    amount: '120',
    method: 'PayPal',
    status: 'APPROVED',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    $id: 'wd_002',
    userId: 'user_001',
    username: 'alex_rivers',
    amount: '75',
    method: 'Bank Transfer',
    status: 'PENDING',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
  },
];

export const MOCK_AUDIT_LOGS = [
  { $id: 'log_001', action: 'POST_DELETED', details: 'Spam content removed', timestamp: new Date(Date.now() - 86400000).toISOString() },
  { $id: 'log_002', action: 'USER_VERIFIED', details: 'maya_chen verified by admin', timestamp: new Date(Date.now() - 86400000 * 3).toISOString() },
];
